/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.faesa.javaclinic_lpoo_c3.view.principal;
import br.faesa.javaclinic_lpoo_c3.view.medico.MenuMedico;
import br.faesa.javaclinic_lpoo_c3.view.paciente.MenuPaciente;
import br.faesa.javaclinic_lpoo_c3.view.consulta.JanelaConsultas;
import br.faesa.javaclinic_lpoo_c3.view.relatorios.JanelaRelatorios;

import java.util.logging.Logger;

/**
 *
 * @author sabri
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(MenuPrincipal.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("JavaClinic - Menu Principal");
    }

    /**
     private void mostrarTela(javax.swing.JPanel tela) {
     panelConteudo.removeAll();
     panelConteudo.setLayout(new java.awt.BorderLayout());
     panelConteudo.add(tela, java.awt.BorderLayout.CENTER);
     panelConteudo.revalidate();
     panelConteudo.repaint();
     }
     COM AS JANELAS CRIADAS, RESOLVI COMENTAR ESSA PARTE QUE, NO MOMENTO, ESTA SEM USO*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        btnConsultas = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnMedicos = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabelSubtitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setMaximumSize(new java.awt.Dimension(100, 100));
        panelMenu.setMinimumSize(new java.awt.Dimension(100, 0));
        panelMenu.setPreferredSize(new java.awt.Dimension(100, 600));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitulo.setText("BEM VINDO AO JAVA CLINIC!");

        btnConsultas.setText("Consultas");
        btnConsultas.addActionListener(this::btnConsultasActionPerformed);

        btnRelatorios.setText("Relatórios");
        btnRelatorios.addActionListener(this::btnRelatoriosActionPerformed);

        btnMedicos.setText("Médicos");
        btnMedicos.addActionListener(this::btnMedicosActionPerformed);

        btnPacientes.setText("Pacientes");
        btnPacientes.addActionListener(this::btnPacientesActionPerformed);

        btnSair.setText("Sair");
        btnSair.addActionListener(this::btnSairActionPerformed);

        jLabelSubtitulo.setText("Selecione uma opção para começar:");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
                panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelMenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPacientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnMedicos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelMenuLayout.createSequentialGroup()
                                                .addComponent(jLabelSubtitulo)
                                                .addGap(0, 6, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabelTitulo)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
                panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabelTitulo)
                                .addGap(28, 28, 28)
                                .addComponent(jLabelSubtitulo)
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMedicos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPacientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRelatorios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(btnSair)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        new JanelaConsultas().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        new JanelaRelatorios().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicosActionPerformed
        new MenuMedico().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnMedicosActionPerformed

    private void btnPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPacientesActionPerformed
        new MenuPaciente().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPacientesActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        int opc = javax.swing.JOptionPane.showConfirmDialog(this,
                "Deseja realmente sair do sistema?",
                "Confirmação",
                javax.swing.JOptionPane.YES_NO_OPTION);
        if (opc == javax.swing.JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnMedicos;
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel panelMenu;
    // End of variables declaration//GEN-END:variables
}
