/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.faesa.javaclinic_lpoo_c3.view.medico;

import br.faesa.javaclinic_lpoo_c3.controller.ControllerMedico;
import br.faesa.javaclinic_lpoo_c3.model.Especialidade;
import br.faesa.javaclinic_lpoo_c3.model.Medico;
import br.faesa.javaclinic_lpoo_c3.view.principal.MenuPrincipal;

import javax.swing.JOptionPane;

/**
 *
 * @author Gessiele Lima
 */
public class AtualizarMedico extends javax.swing.JFrame {
    private ControllerMedico controllerM = new ControllerMedico();
    private String crmOriginal;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AtualizarMedico.class.getName());

    /**
     * Creates new form AtualizarMedico
     */
    public AtualizarMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimparCampoP = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFieldEnderecoMedico = new javax.swing.JTextField();
        ftxtFieldCrmMedico = new javax.swing.JFormattedTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnSalvarMedico = new javax.swing.JButton();
        txtFieldTelefoneMedico = new javax.swing.JTextField();
        txtFieldNomeMedico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtFieldEmailMedico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxEspecialidade = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLimparCampoP.setText("Limpar");
        btnLimparCampoP.addActionListener(this::btnLimparCampoPActionPerformed);

        btnSair.setBackground(new java.awt.Color(204, 0, 0));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSair.setText("Voltar");
        btnSair.addActionListener(this::btnSairActionPerformed);

        jLabel2.setText("CRM do médico:");

        txtFieldEnderecoMedico.addActionListener(this::txtFieldEnderecoMedicoActionPerformed);

        ftxtFieldCrmMedico.setText("  ");
        ftxtFieldCrmMedico.addActionListener(this::ftxtFieldCrmMedicoActionPerformed);

        btnSalvarMedico.setText("Salvar");
        btnSalvarMedico.addActionListener(this::btnSalvarMedicoActionPerformed);

        txtFieldTelefoneMedico.addActionListener(this::txtFieldTelefoneMedicoActionPerformed);

        txtFieldNomeMedico.addActionListener(this::txtFieldNomeMedicoActionPerformed);

        jLabel8.setText("Telefone:");

        jLabel4.setText("Nome completo:");

        txtFieldEmailMedico.addActionListener(this::txtFieldEmailMedicoActionPerformed);

        jLabel5.setText("E-mail:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Editar Dados");

        jLabel7.setText("Endereço:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Atualizar Médico");
        jLabel1.setToolTipText("");

        jComboBoxEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARDIOLOGIA", "PEDIATRIA", "DERMATOLOGIA", "ORTOPEDIA", "GINECOLOGIA", "" }));

        jLabel6.setText("Especialidade:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtFieldEmailMedico, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldNomeMedico, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldEnderecoMedico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFieldTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxEspecialidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ftxtFieldCrmMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(190, 190, 190)
                            .addComponent(btnSalvarMedico)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnLimparCampoP)
                            .addGap(0, 290, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ftxtFieldCrmMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFieldNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldEmailMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldEnderecoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtFieldTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnSair)
                    .addGap(303, 303, 303)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSalvarMedico)
                        .addComponent(btnLimparCampoP))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparCampoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCampoPActionPerformed
        ftxtFieldCrmMedico.setText("");
        txtFieldNomeMedico.setText("");
        txtFieldEmailPaciente.setText("");
        txtFieldTelefoneMedico.setText("");
        jComboBoxEspecialidade.setSelectedIndex(0);
    }//GEN-LAST:event_btnLimparCampoPActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        MenuMedico telaMM = new MenuMedico();
        telaMM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtFieldEnderecoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEnderecoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEnderecoMedicoActionPerformed

    private void ftxtFieldCrmMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftxtFieldCrmMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftxtFieldCrmMedicoActionPerformed

    private void btnSalvarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarMedicoActionPerformed
        String crm = ftxtFieldCrmMedico.getText().trim();
        String nome = txtFieldNomeMedico.getText().trim();
        String email = txtFieldEmailMedico.getText().trim();
        String telefone = txtFieldTelefoneMedico.getText().trim();
        String endereco = txtFieldEnderecoMedico.getText().trim();
        Especialidade especialidade = (Especialidade) jComboBoxEspecialidade.getSelectedItem();

        ControllerMedico controllerM = new ControllerMedico();

        if (crm.isEmpty() || nome.isEmpty() || email.isEmpty() || telefone.isEmpty() || endereco.isEmpty() || especialidade == null) {
            JOptionPane.showMessageDialog(this,
                    "Preencha todos os campos e selecione uma especialidade!",
                    "Erro de Validação",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        Medico m = new Medico(nome, email, endereco, telefone, crm, especialidade);

        // CHAMADA CERTA (somente uma vez!)
        boolean atualizado = controllerM.atualizar(m);

        if (atualizado) {
            JOptionPane.showMessageDialog(this,
                "Médico atualizado com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                "Não foi possível atualizar o médico.\nVerifique se o CRM já está cadastrado.",
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarMedicoActionPerformed

    private void txtFieldTelefoneMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTelefoneMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTelefoneMedicoActionPerformed

    private void txtFieldNomeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNomeMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNomeMedicoActionPerformed

    private void txtFieldEmailMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEmailMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEmailMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AtualizarMedico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparCampoP;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvarMedico;
    private javax.swing.JFormattedTextField ftxtFieldCrmMedico;
    protected javax.swing.JComboBox<String> jComboBoxEspecialidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField txtFieldEmailMedico;
    private javax.swing.JTextField txtFieldEmailPaciente;
    private javax.swing.JTextField txtFieldEmailPaciente1;
    private javax.swing.JTextField txtFieldEmailPaciente2;
    private javax.swing.JTextField txtFieldEmailPaciente3;
    private javax.swing.JTextField txtFieldEmailPaciente4;
    private javax.swing.JTextField txtFieldEmailPaciente5;
    private javax.swing.JTextField txtFieldEmailPaciente6;
    private javax.swing.JTextField txtFieldEmailPaciente7;
    private javax.swing.JTextField txtFieldEnderecoMedico;
    private javax.swing.JTextField txtFieldNomeMedico;
    private javax.swing.JTextField txtFieldTelefoneMedico;
    // End of variables declaration//GEN-END:variables
}
