/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.faesa.javaclinic_lpoo_c3.view.medico;

import br.faesa.javaclinic_lpoo_c3.controller.ControllerMedico;
import br.faesa.javaclinic_lpoo_c3.controller.ControllerPaciente;
import br.faesa.javaclinic_lpoo_c3.model.Especialidade;
import br.faesa.javaclinic_lpoo_c3.model.Medico;
import javax.swing.JOptionPane;

/**
 *
 * @author Gessiele Lima
 */
public class CadastrarMedico extends javax.swing.JFrame {

    private ControllerMedico controllerM = new ControllerMedico();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastrarMedico.class.getName());

    /**
     * Creates new form CadastrarMedico
     */
    public CadastrarMedico() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Cadastrar Médico - JavaClinic");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvarPaciente = new javax.swing.JButton();
        txtFieldNomeMedico = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtFieldEmailMedico = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldEnderecoMedico = new javax.swing.JTextField();
        txtFieldTelefoneMedico = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnLimparCampoP = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCrmMed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbEspecialidadeM = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalvarPaciente.setText("Salvar");
        btnSalvarPaciente.addActionListener(this::btnSalvarPacienteActionPerformed);

        txtFieldNomeMedico.addActionListener(this::txtFieldNomeMedicoActionPerformed);

        btnSair.setBackground(new java.awt.Color(136, 185, 220));
        btnSair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSair.setText("Voltar");
        btnSair.addActionListener(this::btnSairActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.setText("Nome completo:");

        txtFieldEmailMedico.addActionListener(this::txtFieldEmailMedicoActionPerformed);

        jLabel5.setText("E-mail:");

        txtFieldEnderecoMedico.addActionListener(this::txtFieldEnderecoMedicoActionPerformed);

        txtFieldTelefoneMedico.addActionListener(this::txtFieldTelefoneMedicoActionPerformed);

        jLabel7.setText("Endereço:");

        jLabel6.setText("Telefone:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastrar Médico");
        jLabel1.setToolTipText("");

        btnLimparCampoP.setText("Limpar");
        btnLimparCampoP.addActionListener(this::btnLimparCampoPActionPerformed);

        jLabel2.setText("CRM");

        txtCrmMed.addActionListener(this::txtCrmMedActionPerformed);

        jLabel3.setText("Especialidades:");

        cbEspecialidadeM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARDIOLOGIA", "PEDIATRIA", "DERMATOLOGIA", "ORTOPEDIA", "GINECOLOGIA", " " }));

        try {
            txtFieldTelefoneMedico.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFieldEmailMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtFieldTelefoneMedico)
                                        .addGap(84, 84, 84))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(552, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCrmMed, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtFieldNomeMedico)))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbEspecialidadeM, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(84, 84, 84))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 306, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtFieldEnderecoMedico))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(459, Short.MAX_VALUE)
                        .addComponent(btnSalvarPaciente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimparCampoP)))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCrmMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFieldNomeMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldEmailMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldTelefoneMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldEnderecoMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEspecialidadeM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarPaciente)
                    .addComponent(btnLimparCampoP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPacienteActionPerformed
        String crm = txtCrmMed.getText();
        String nome = txtFieldNomeMedico.getText();
        String email = txtFieldEmailMedico.getText();
        String telefone = txtFieldTelefoneMedico.getText();
        
        String txtEspecialidade = cbEspecialidadeM.getSelectedItem().toString();
        Especialidade especialidade = Especialidade.fromString(txtEspecialidade);
        
        String endereco = txtFieldEnderecoMedico.getText(); // *** ADICIONADO ***

        if (crm.isEmpty() || nome.isEmpty() || email.isEmpty() || telefone.isEmpty() ||
            txtEspecialidade.isEmpty() || endereco.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(this,
                    "Preencha todos os campos!",
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // String nome, String email, String endereco, String telefone, String crm, Especialidade especialidade
        Medico medico = new Medico(nome, email, endereco, telefone, crm, especialidade);

        boolean sucesso = controllerM.inserir(medico);

        if (sucesso) {
            javax.swing.JOptionPane.showMessageDialog(this, "Médico cadastrado com sucesso!");
            btnLimparCampoPActionPerformed(null);
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Erro ao cadastrar médico! Verifique o CRM.",
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarPacienteActionPerformed

    private void txtFieldNomeMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldNomeMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldNomeMedicoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        MenuMedico telaMM = new MenuMedico();
        telaMM.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void txtFieldEmailMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEmailMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEmailMedicoActionPerformed

    private void txtFieldEnderecoMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEnderecoMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEnderecoMedicoActionPerformed

    private void txtFieldTelefoneMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldTelefoneMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldTelefoneMedicoActionPerformed

    private void btnLimparCampoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCampoPActionPerformed
        txtCrmMed.setText("");
        txtFieldNomeMedico.setText("");
        txtFieldEmailMedico.setText("");
        txtFieldTelefoneMedico.setText("");
        txtFieldEnderecoMedico.setText("");
        cbEspecialidadeM.setAction(null);

    }//GEN-LAST:event_btnLimparCampoPActionPerformed

    private void txtCrmMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCrmMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCrmMedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastrarMedico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparCampoP;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvarPaciente;
    private javax.swing.JComboBox<String> cbEspecialidadeM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCrmMed;
    private javax.swing.JTextField txtFieldEmailMedico;
    private javax.swing.JTextField txtFieldEnderecoMedico;
    private javax.swing.JTextField txtFieldNomeMedico;
    private javax.swing.JFormattedTextField txtFieldTelefoneMedico;
    // End of variables declaration//GEN-END:variables
}
