/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.faesa.javaclinic_lpoo_c3.view;

import br.faesa.javaclinic_lpoo_c3.reports.Relatorios;
import br.faesa.javaclinic_lpoo_c3.controller.ControllerMedico;
import br.faesa.javaclinic_lpoo_c3.controller.ControllerPaciente;

import javax.swing.*;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.Scanner;

/**
 *
 * @author sabri
 */
public class TelaRelatorios extends javax.swing.JPanel {
    private final Relatorios relatorios = new Relatorios();
    private final ControllerMedico ctrlMedico = new ControllerMedico();
    private final ControllerPaciente ctrlPaciente = new ControllerPaciente();

    /**
     * Creates new form TelaRelatorios
     */
    public TelaRelatorios() {
        initComponents();
    }
    
        /**
     * Executa um relatório que imprime em System.out,
     * captura a saída e joga no txtResultado.
     */
    private void executarRelatorio(Runnable acaoRelatorio) {
        try {
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            PrintStream ps = new PrintStream(baos);
            PrintStream antigo = System.out;

            System.setOut(ps);          // redireciona System.out
            acaoRelatorio.run();        // executa o método que imprime
            System.out.flush();
            System.setOut(antigo);      // devolve System.out

            String texto = baos.toString();
            txtResultado.setText(texto);

        } catch (Exception ex) {
            txtResultado.setText("Erro ao gerar relatório: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenuRelatorios = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGeralPessoas = new javax.swing.JButton();
        btnEspecialidade = new javax.swing.JButton();
        btnMedico = new javax.swing.JButton();
        btnDetalhadas = new javax.swing.JButton();
        btnHistoricoPaciente = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        panelResultados = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTitulo.setText("RELATÓRIOS");

        jLabel2.setText("CPF do paciente:");

        btnGeralPessoas.setText("Relatório Geral de Pessoas");
        btnGeralPessoas.addActionListener(this::btnGeralPessoasActionPerformed);

        btnEspecialidade.setText("Consultas por Especialidade");
        btnEspecialidade.addActionListener(this::btnEspecialidadeActionPerformed);

        btnMedico.setText("Consultas por Médico");
        btnMedico.addActionListener(this::btnMedicoActionPerformed);

        btnDetalhadas.setText("Consultas Detalhadas");
        btnDetalhadas.addActionListener(this::btnDetalhadasActionPerformed);

        btnHistoricoPaciente.setText("Histórico do Paciente");
        btnHistoricoPaciente.addActionListener(this::btnHistoricoPacienteActionPerformed);

        btnVoltar.setText("Voltar ao Menu Principal");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        javax.swing.GroupLayout panelMenuRelatoriosLayout = new javax.swing.GroupLayout(panelMenuRelatorios);
        panelMenuRelatorios.setLayout(panelMenuRelatoriosLayout);
        panelMenuRelatoriosLayout.setHorizontalGroup(
            panelMenuRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuRelatoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuRelatoriosLayout.createSequentialGroup()
                        .addGroup(panelMenuRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDetalhadas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMenuRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnEspecialidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGeralPessoas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnMedico, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(panelMenuRelatoriosLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabelTitulo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelMenuRelatoriosLayout.createSequentialGroup()
                        .addGroup(panelMenuRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuRelatoriosLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCpf))
                            .addComponent(btnHistoricoPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelMenuRelatoriosLayout.setVerticalGroup(
            panelMenuRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuRelatoriosLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGeralPessoas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEspecialidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMedico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDetalhadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuRelatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistoricoPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addContainerGap())
        );

        txtResultado.setColumns(20);
        txtResultado.setRows(5);
        jScrollPane2.setViewportView(txtResultado);

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenuRelatorios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenuRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEspecialidadeActionPerformed
        executarRelatorio(() -> relatorios.gerarRelatorioConsultasPorEspecialidade());
    }//GEN-LAST:event_btnEspecialidadeActionPerformed

    private void btnGeralPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeralPessoasActionPerformed
        executarRelatorio(() -> relatorios.gerarRelatorioGeralPessoas(ctrlMedico, ctrlPaciente));
    }//GEN-LAST:event_btnGeralPessoasActionPerformed

    private void btnMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicoActionPerformed
        executarRelatorio(() -> relatorios.gerarRelatorioConsultasPorMedico());
    }//GEN-LAST:event_btnMedicoActionPerformed

    private void btnDetalhadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalhadasActionPerformed
        executarRelatorio(() -> relatorios.gerarRelatorioConsultasDetalhadas());
    }//GEN-LAST:event_btnDetalhadasActionPerformed

    private void btnHistoricoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoPacienteActionPerformed
        String cpf = txtCpf.getText().trim();

        if (cpf.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Informe o CPF do paciente.",
                "Atenção",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        Scanner sc = new Scanner(cpf + "\n");

        executarRelatorio(() -> relatorios.gerarRelatorioHistoricoPaciente(sc));
    }//GEN-LAST:event_btnHistoricoPacienteActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        java.awt.Window janela = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (janela != null) {
            janela.dispose();
        }

        new MenuPrincipal().setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalhadas;
    private javax.swing.JButton btnEspecialidade;
    private javax.swing.JButton btnGeralPessoas;
    private javax.swing.JButton btnHistoricoPaciente;
    private javax.swing.JButton btnMedico;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelMenuRelatorios;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
